import { chromium, expect } from '@playwright/test'
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import path from 'node:path'
import os from 'node:os'
import assert from 'node:assert/strict'
import { createDeviceServer } from '../src/device/server.mjs'
import { DeviceService } from '../src/device/service.mjs'
import { createKernel } from '../src/kernel/index.mjs'

const temp = await mkdtemp(path.join(os.tmpdir(), 'kkcode-web-smoke-')), previous = process.env.KKCODE_HOME
const executeFile = promisify(execFile), workspace = path.join(temp, 'workspace'), requests = []
await mkdir(workspace)
const git = args => executeFile('git', ['-c', `core.hooksPath=${path.join(temp, 'disabled-hooks')}`, '-c', 'commit.gpgsign=false', ...args], { cwd: workspace })
await git(['init', '-b', 'main'])
await writeFile(path.join(workspace, 'README.md'), 'Browser acceptance fixture\n')
await git(['add', 'README.md'])
await git(['-c', 'user.name=KK Code UI Test', '-c', 'user.email=24042203053@ecupl.edu.cn', 'commit', '-m', 'Browser acceptance fixture'])
await git(['branch', 'feature/existing'])
process.env.KKCODE_HOME = path.join(temp, 'state')
await mkdir(process.env.KKCODE_HOME)
await writeFile(path.join(process.env.KKCODE_HOME, 'config.json'), JSON.stringify({ provider: { default: 'openai', openai: { default_model: 'fixture' } }, skills: { auto_seed: false }, mcp: { auto_discover: false } }))
const service = await new DeviceService({ cwd: workspace, roots: [workspace], createKernelImpl: async options => {
  const kernel = await createKernel({ ...options, trustState: { trusted: true } })
  kernel.providers.registerProvider('openai', { async request(...args) { requests.push(args); return { text: '**Connected.**\n\nThis response came through the real device turn API.', toolCalls: [], usage: { input: 1, output: 1 } } }, async *requestStream() { yield { type: 'text', content: '**Connected.**\n\nThis response came through the real device turn API.' } } })
  kernel.configState.config.provider.openai.stream = false
  return kernel
} }).initialize()
const server = await createDeviceServer({ service, port: 0 }), apiErrors = []
server.app.addHook('onError', (request, _reply, error, done) => { apiErrors.push({ method: request.body?.method, code: error.code, message: error.message, stack: error.stack }); done() })
const info = await server.listen()
const browser = await chromium.launch({ headless: true, ...(process.env.KKCODE_CHROMIUM ? { executablePath: process.env.KKCODE_CHROMIUM } : {}) })
let activePage
try {
  await mkdir(path.resolve('test-results'), { recursive: true })
  const unauthenticated = await browser.newPage({ viewport: { width: 390, height: 844 } })
  await unauthenticated.goto(info.address)
  await expect(unauthenticated.getByText('你的对话，在这里继续')).toBeVisible()
  await expect(unauthenticated.getByRole('dialog')).toHaveCount(0)
  await expect(unauthenticated.getByLabel('配对码', { exact: true })).toHaveCount(0)
  await expect(unauthenticated.locator('input[type=password]')).toHaveCount(0)
  await unauthenticated.screenshot({ animations: 'disabled', path: 'test-results/web-startup.png' })
  await unauthenticated.getByRole('button', { name: '更多', exact: true }).click()
  await unauthenticated.getByRole('menuitem', { name: '设置', exact: true }).click()
  await expect(unauthenticated.getByRole('dialog')).toBeVisible()
  await expect(unauthenticated.getByLabel('配对码', { exact: true })).toHaveCount(0)
  await unauthenticated.getByRole('dialog').getByRole('button', { name: '添加连接', exact: true }).click()
  await expect(unauthenticated.getByLabel('配对码', { exact: true })).toBeVisible()
  await unauthenticated.keyboard.press('Escape')
  await expect(unauthenticated.getByRole('dialog')).toHaveCount(0)
  await unauthenticated.close()
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
  const page = await context.newPage()
  activePage = page
  const errors = []; page.on('pageerror', e => errors.push(e.message))
  const externalRequests = []
  page.on('request', request => { if (!request.url().startsWith(info.address)) externalRequests.push(request.url()) })
  await page.goto(info.url)
  await page.getByRole('textbox', { name: '消息' }).waitFor()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('input[type=password]')).toHaveCount(0)
  await page.getByRole('textbox', { name: '消息' }).fill('Hello from browser')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await page.getByText('Connected.', { exact: false }).first().waitFor({ timeout: 15000 })
  await expect(page.locator('.message.assistant')).toHaveCount(1)
  await expect(page.locator('.message.user')).toHaveCount(1)
  await page.screenshot({ animations: 'disabled', path: 'test-results/web-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '返回会话列表' }).click()
  await expect(page.getByRole('textbox', { name: '搜索聊天' })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.screenshot({ animations: 'disabled', path: 'test-results/web-home.png' })
  await page.getByRole('button', { name: '更多', exact: true }).click()
  await page.screenshot({ animations: 'disabled', path: 'test-results/web-menu.png' })
  await page.getByRole('menuitem', { name: '设置', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('heading', { name: '设置', exact: true })).toBeVisible()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveCount(0)
  await page.screenshot({ animations: 'disabled', path: 'test-results/web-settings.png' })
  await dialog.getByRole('button', { name: '模型与渠道', exact: true }).click()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: '添加渠道', exact: true }).click()
  await expect(page.getByLabel('API Key', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: '返回上一级' }).click()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveCount(0)
  await page.keyboard.press('Tab')
  assert.equal(await page.evaluate(() => Boolean(document.activeElement.closest('[role=dialog]'))), true)
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  assert.equal(await page.locator('#root').evaluate(element => element.inert), false)
  await page.getByRole('textbox', { name: '搜索聊天' }).fill('not-a-session')
  await expect(page.getByText('没有找到相关对话')).toBeVisible()
  await page.getByRole('textbox', { name: '搜索聊天' }).fill('')
  await page.locator('.remote-session').first().click()
  await expect(page.locator('.message.assistant')).toHaveCount(1)
  const input = page.getByRole('textbox', { name: '消息' })
  await input.fill('/pl')
  await expect(page.getByRole('listbox', { name: '命令建议' })).toBeVisible()
  await input.press('Tab')
  await expect(input).toHaveValue('/plan ')
  await input.fill('/')
  await input.press('Escape')
  await expect(page.getByRole('listbox', { name: '命令建议' })).toHaveCount(0)
  await input.fill('')
  await page.getByRole('button', { name: '添加与工具', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: '工作目录', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  const [current] = await service.dispatch('sessions.list', {}, { id: 'local', client: 'local' })
  // UI fixture events, not a claim that a real model edited these files.
  await service.record({ type: 'tool.start', sessionId: current.id, turnId: 'ui-fixture', payload: { invocationId: 'ui-edit', tool: 'edit', args: { file_path: '/workspace/main.ts' } } })
  await service.record({ type: 'tool.finish', sessionId: current.id, turnId: 'ui-fixture', payload: { invocationId: 'ui-edit', tool: 'edit', status: 'completed', durationMs: 42, metadata: { mutations: [{ filePath: '/workspace/main.ts', addedLines: 1, removedLines: 1, structuredPatch: [{ oldStart: 1, oldLineCount: 1, newStart: 1, newLineCount: 1, lines: [{ type: 'remove', text: 'const oldValue = true' }, { type: 'add', text: 'const newValue = true' }] }] }] } } })
  await expect(page.locator('.tool-row')).toHaveCount(1)
  await expect(page.getByText('已编辑 main.ts', { exact: true })).toBeVisible()
  await expect(page.locator('.diff-add')).not.toBeVisible()
  await page.getByText('已编辑 main.ts', { exact: true }).click()
  await expect(page.locator('.diff-add')).toBeVisible()
  await expect(page.locator('.diff-remove')).toBeVisible()
  await expect(page.getByRole('textbox', { name: '消息' })).toBeInViewport()
  await page.screenshot({ animations: 'disabled', path: 'test-results/web-diff.png' })
  await page.getByText('已编辑 main.ts', { exact: true }).click()
  await expect(page.locator('.diff-add')).not.toBeVisible()
  await service.record({ type: 'stream.thinking.delta', sessionId: current.id, turnId: 'ui-fixture', payload: { text: 'Thinking content is collapsed by default.' } })
  await service.record({ type: 'stream.text.delta', sessionId: current.id, turnId: 'ui-fixture', payload: { text: '### Updated\n\nA compact, expandable activity timeline.' } })
  await expect(page.locator('.thinking-row')).toHaveCount(1)
  await expect(page.getByText('Thinking content is collapsed by default.', { exact: true })).not.toBeVisible()
  await page.locator('.thinking-row > summary').click()
  await expect(page.getByText('Thinking content is collapsed by default.', { exact: true })).toBeVisible()
  await page.locator('.thinking-row > summary').click()
  await expect(page.getByRole('heading', { name: 'Updated' })).toBeVisible()
  await page.screenshot({ animations: 'disabled', path: 'test-results/web-mobile.png', fullPage: true })
  await input.fill('/pl')
  await page.screenshot({ animations: 'disabled', path: 'test-results/web-commands.png' })
  await input.fill('')
  await page.getByRole('button', { name: '添加与工具', exact: true }).click()
  await page.getByRole('menuitem', { name: '添加附件', exact: true }).click()
  await dialog.getByLabel('选择附件').setInputFiles({ name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('REAL_BROWSER_ATTACHMENT_ACCEPTANCE') })
  await expect(dialog.getByText('notes.txt', { exact: true })).toBeVisible()
  assert.equal((await service.dispatch('attachments.list', { sessionId: current.id }, { id: 'local', client: 'local' })).attachments.length, 1)
  await page.keyboard.press('Escape')
  await input.fill('Read my attachment')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await expect.poll(() => requests.some(request => JSON.stringify(request).includes('REAL_BROWSER_ATTACHMENT_ACCEPTANCE'))).toBe(true)
  await expect(page.getByRole('button', { name: '停止', exact: true })).toHaveCount(0)
  await expect(page.locator('.attachment-summary')).toHaveCount(0)
  // Two authenticated clients must converge after destructive conversation edits.
  const mirror = await page.context().newPage()
  await mirror.setViewportSize({ width: 390, height: 844 }); await mirror.goto(info.address)
  await mirror.locator('.remote-session').first().click()
  await expect(mirror.locator('.message.user')).toHaveCount(2)
  await page.getByRole('button', { name: '从这条提问回退' }).last().click()
  await expect(dialog).toContainText('不会撤销任何文件或 Git 修改')
  await dialog.getByRole('button', { name: '确认回退对话' }).click()
  await expect(input).toHaveValue(/Read my attachment/)
  await expect(page.locator('.message.user')).toHaveCount(1)
  await expect(mirror.locator('.message.user')).toHaveCount(1)
  await input.fill('')
  await page.getByRole('button', { name: '对话设置' }).click()
  await dialog.getByLabel('对话名称').fill('手动名称优先 · 会话验收')
  await dialog.getByRole('button', { name: '保存名称' }).click()
  await expect(mirror.locator('.chat-title strong')).toHaveText('手动名称优先 · 会话验收')
  await page.getByRole('button', { name: '对话设置' }).click()
  await dialog.getByRole('button', { name: /^归档对话/ }).click()
  await expect.poll(async () => (await service.dispatch('sessions.get', { sessionId: current.id }, { id: 'local', client: 'local' })).archived).toBe(true)
  await expect(mirror.getByRole('textbox', { name: '消息' })).toBeDisabled()
  await page.getByRole('button', { name: '返回会话列表' }).click()
  await expect(page.locator('.remote-session')).toHaveCount(0)
  await page.getByRole('button', { name: '更多', exact: true }).click()
  await page.getByRole('menuitem', { name: '已归档对话', exact: true }).click()
  await page.getByRole('button', { name: '管理对话 手动名称优先 · 会话验收' }).click()
  await dialog.getByRole('button', { name: /^恢复到对话列表/ }).click()
  await expect(page.locator('.remote-session')).toHaveCount(0)
  await page.getByRole('button', { name: '更多', exact: true }).click()
  await page.getByRole('menuitem', { name: '全部对话', exact: true }).click()
  await page.locator('.remote-session').first().click()
  await expect(mirror.getByRole('textbox', { name: '消息' })).toBeEditable()
  await mirror.close()
  // Legacy SVG bytes stay private in history; clients receive only an authenticated raster preview.
  const mediaKernel = await service.kernel(workspace)
  const legacySvg = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="48" height="32"><rect width="48" height="32" fill="red"/></svg>').toString('base64')
  await mediaKernel.run(() => mediaKernel.sessions.appendMessage(current.id, 'user', [{ type: 'image', data: legacySvg, mediaType: 'image/svg+xml' }], { synthetic: true }))
  await page.reload(); await page.locator('.remote-session').first().click()
  await expect(page.locator('.media-preview img')).toHaveCount(0)
  await page.locator('.media-preview summary').click()
  await expect(page.locator('.media-preview img')).toBeVisible()
  await expect.poll(() => page.locator('.media-preview img').evaluate(img => img.naturalWidth)).toBe(48)
  assert.match(await page.locator('.media-preview img').getAttribute('src'), /^data:image\/png;base64,/)
  await expect(page.getByRole('button', { name: /^操作权限/ })).toHaveCount(0)
  await page.getByRole('button', { name: /^执行模式，当前/ }).click()
  await page.getByRole('menuitemradio', { name: /^Auto / }).click()
  await expect(page.getByRole('button', { name: '执行模式，当前 Auto' })).toBeVisible()
  assert.equal((await service.dispatch('sessions.get', { sessionId: current.id }, { id: 'local', client: 'local' })).modeId, 'auto')
  await input.fill('/profile edit'); await page.getByRole('button', { name: '发送', exact: true }).click()
  await dialog.getByLabel('常用语言（逗号分隔）').fill('中文, English')
  await dialog.getByRole('button', { name: '保存偏好', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  assert.deepEqual((await service.dispatch('profile.get', {}, { id: 'local', client: 'local' })).languages, ['中文', 'English'])
  await input.fill('/keys'); await page.getByRole('button', { name: '发送', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('终端快捷键只在 CLI 中提供'); await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: '添加与工具', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Git 分支', exact: true }).click()
  await dialog.getByRole('button', { name: /^feature\/existing / }).click()
  assert.equal((await git(['branch', '--show-current'])).stdout.trim(), 'main')
  await dialog.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(dialog.getByText(/当前：feature\/existing/)).toBeVisible()
  assert.equal((await git(['branch', '--show-current'])).stdout.trim(), 'feature/existing')
  await dialog.getByLabel('新分支名称').fill('feature/browser-created')
  await dialog.getByRole('button', { name: '创建并切换分支', exact: true }).click()
  await dialog.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(dialog.getByText(/当前：feature\/browser-created/)).toBeVisible()
  assert.equal((await git(['branch', '--show-current'])).stdout.trim(), 'feature/browser-created')
  await writeFile(path.join(workspace, 'README.md'), 'An uncommitted change must survive\n')
  await dialog.getByRole('button', { name: '刷新 Git 状态', exact: true }).click()
  await expect(dialog.getByRole('button', { name: /^main / })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Worktree', exact: true }).click()
  await dialog.getByLabel('新分支名称', { exact: true }).fill('feature/worktree-ui')
  await dialog.getByLabel('Worktree 父目录', { exact: true }).fill(workspace)
  await dialog.getByLabel('新文件夹名称', { exact: true }).fill('ui-worktree')
  await dialog.getByRole('button', { name: '创建 Worktree', exact: true }).click()
  await dialog.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(dialog.getByRole('button', { name: /^feature\/worktree-ui / })).toBeVisible()
  assert.equal(await readFile(path.join(workspace, 'README.md'), 'utf8'), 'An uncommitted change must survive\n')
  assert.equal(await readFile(path.join(workspace, 'ui-worktree', 'README.md'), 'utf8'), 'Browser acceptance fixture\n')
  await dialog.getByRole('button', { name: /^feature\/worktree-ui / }).click()
  await dialog.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.chat-title button')).toContainText('ui-worktree')
  assert.equal((await service.dispatch('sessions.get', { sessionId: current.id }, { id: 'local', client: 'local' })).cwd, workspace)
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 320, height: 568 })
  assert.equal(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth), true)
  await page.getByRole('button', { name: '返回会话列表' }).click()
  await page.getByRole('button', { name: '聊天', exact: true }).click()
  await dialog.getByRole('button', { name: /^工作目录/ }).click()
  await dialog.getByRole('button', { name: '选择此目录', exact: true }).click()
  await expect(dialog.getByRole('heading', { name: '新对话', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('textbox', { name: '搜索聊天' })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  assert.deepEqual(externalRequests, [])
  assert.deepEqual(errors, [])
  console.log('Web real device API: two-client rewind/rename/archive/restore, authenticated SVG-to-PNG preview, unified Auto selector, Git branches/worktree creation/open with dirty-source preservation, turns/attachments/profile, hidden settings, focus/Escape, folded activity and 320px layout passed')
} catch (error) {
  await activePage?.screenshot({ path: 'test-results/web-failure.png', fullPage: true }).catch(() => {})
  if (apiErrors.length) console.error('Isolated browser fixture API diagnostics:', JSON.stringify(apiErrors))
  throw error
} finally { await browser.close(); await server.close(); if (previous === undefined) delete process.env.KKCODE_HOME; else process.env.KKCODE_HOME = previous; await rm(temp, { recursive: true, force: true }) }
