import { pixelBuddySvg, pixelStudioSvg } from '../ui/pixel-art.mjs'

const escape = value => String(value).replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]))

/** The body is server-authored markup; every interpolated account/code is escaped at its call site. */
export function gatewayPage(title, body) {
  const step = title === '组织登录' ? 1 : title === '确认连接' ? 2 : 3
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark light"><title>${escape(title)} · KK Code</title><style>
  :root{color-scheme:dark;--bg:#0d1311;--panel:#18221d;--line:#2c3b34;--text:#ecefe6;--muted:#a6b3a8;--gold:#e6bb75;--ink:#292719;--soft:#202f24}
  *{box-sizing:border-box}body{margin:0;color:var(--text);background:var(--bg);font:15px "Noto Sans SC","Microsoft YaHei",-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;min-height:100vh;padding:28px 20px}
  .brand{display:flex;align-items:center;gap:10px;max-width:1080px;margin:0 auto;font-size:20px;font-weight:700;letter-spacing:-.5px}.brand svg{width:32px;height:36px}.brand em{font-style:normal;color:var(--gold)}.brand small{margin-left:auto;font:10px ui-monospace,monospace;color:var(--muted);letter-spacing:1.5px}
  .gateway-shell{max-width:920px;margin:8vh auto 4vh;display:grid;grid-template-columns:1fr 1.15fr;align-items:center;gap:64px}.gateway-art{text-align:center}.gateway-art svg{width:100%;max-width:340px}.eyebrow{font:10px ui-monospace,monospace;letter-spacing:2px;color:var(--gold);margin:16px 0}.gateway-art h2{font-size:28px;line-height:1.5;letter-spacing:-1px;margin:16px 0}.gateway-art p{font-size:13px}
  main{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:32px;min-width:0;position:relative}main:before{content:"";position:absolute;top:-1px;left:24px;width:48px;height:3px;background:var(--gold)}
  .steps{display:flex;gap:9px;margin-bottom:30px}.steps span{flex:1;border-bottom:2px solid var(--line);padding-bottom:10px;font-size:10px;color:var(--muted)}.steps .active{border-color:var(--gold);color:var(--gold)}h1{font-size:25px;line-height:1.4;letter-spacing:-.6px;margin:0 0 16px}p{line-height:1.85;color:var(--muted);overflow-wrap:anywhere}label{display:block;font-size:12px;color:var(--muted);line-height:1.8}input,button{font:inherit;border-radius:8px;padding:14px;border:1px solid var(--line);width:100%}input{display:block;background:var(--bg);color:var(--text);margin:10px 0 18px;min-width:0;letter-spacing:5px;font:21px ui-monospace,monospace;text-align:center}input[type=hidden]{display:none}button,.primary-link{display:block;text-align:center;cursor:pointer;background:var(--gold);color:var(--ink);font-weight:600;margin-top:20px;border:1px solid var(--gold);border-radius:8px;text-decoration:none;padding:14px;line-height:1.6}button:hover,.primary-link:hover{filter:brightness(1.1)}button small{display:block;font-size:10px;font-weight:400;opacity:.8}a{color:var(--gold);text-underline-offset:4px}a:focus-visible,input:focus-visible,button:focus-visible{outline:2px solid var(--gold);outline-offset:4px}.caption{display:block;font:10px ui-monospace,monospace;letter-spacing:1px;color:var(--muted);margin-bottom:12px}.gateway-footer{text-align:center;font:10px ui-monospace,monospace;letter-spacing:1.5px;color:var(--muted);max-width:920px;margin:36px auto 0}
  @media(prefers-color-scheme:light){:root{color-scheme:light;--bg:#f5f1e7;--panel:#fffcf3;--line:#b8bca5;--text:#29382e;--muted:#637063;--gold:#345b46;--ink:#fffcf3;--soft:#e4ddca}}
  @media(max-width:700px){body{padding:22px 18px}.brand small{font-size:8px}.gateway-shell{grid-template-columns:1fr;gap:22px;max-width:440px;margin:26px auto}.gateway-art svg{width:170px}.gateway-art h2,.gateway-art p{display:none}.gateway-art .eyebrow{margin:6px 0}main{padding:25px}.gateway-footer{font-size:8px;letter-spacing:1px;margin-top:26px}}
  @media(max-height:650px) and (max-width:700px){.gateway-art{display:none}.gateway-shell{margin-top:24px}}
  </style></head><body><div class="brand">${pixelBuddySvg}<span>KK <em>Code</em></span><small>PIXEL STUDIO / CONNECT</small></div><div class="gateway-shell"><div class="gateway-art" aria-hidden="true">${pixelStudioSvg}<div class="eyebrow">A LITTLE SPACE FOR BIG IDEAS</div><h2>你的工作台，<br>下一站就绪。</h2><p>连接熟悉的电脑，让创作继续。</p></div><main><nav class="steps" aria-label="连接进度"><span class="${step === 1 ? 'active' : ''}" ${step === 1 ? 'aria-current="step"' : ''}>01 · 登录</span><span class="${step === 2 ? 'active' : ''}" ${step === 2 ? 'aria-current="step"' : ''}>02 · 确认</span><span class="${step === 3 ? 'active' : ''}" ${step === 3 ? 'aria-current="step"' : ''}>03 · 返回</span></nav>${body}</main></div><footer class="gateway-footer">KK CODE · YOUR WORKSPACE, YOUR CONTROL.</footer></body></html>`
}
